apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
      - name: mail-service
        image: 'bebofit/mail-service-go:1.0.0'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: MAIL_PORT
            value: "1025"
          - name: MAIL_DOMAIN
            value: "localhost"
          - name: MAIL_HOST
            value: "mailhog"
          - name: MAIL_ENCRYPTION
            value: "none"
          - name: MAIL_USERNAME
            value: ""
          - name: MAIL_PASSWORD
            value: ""
          - name: FROM_NAME
            value: "Abe Solyman"
          - name: FROM_ADDRESS
            value: "abesolyman@abesolyman.com"
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail-service
  ports:
  - protocol: TCP
    name: main-port
    port: 80
    targetPort: 80
